<a href="https://colab.research.google.com/github/ashishtekam/ashishtekam/blob/main/Car_Price_Prediction_using_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Car Price Prediction Using Linear Regression

#Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter('ignore')

#Import CSV as Dataframe

In [ ]:
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Car%20Price.csv')

#Get First Five Rows of Dataframe

In [ ]:
df.head()

Brand                     Model  Year  Selling_Price  KM_Driven    Fuel  \
0   Maruti             Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2  Hyundai      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3   Datsun    Datsun RediGO T Option  2017         250000      46000  Petrol   
4    Honda     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  Seller_Type Transmission         Owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner

#Get Information of Dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Brand          4340 non-null   object
 1   Model          4340 non-null   object
 2   Year           4340 non-null   int64 
 3   Selling_Price  4340 non-null   int64 
 4   KM_Driven      4340 non-null   int64 
 5   Fuel           4340 non-null   object
 6   Seller_Type    4340 non-null   object
 7   Transmission   4340 non-null   object
 8   Owner          4340 non-null   object
dtypes: int64(3), object(6)
memory usage: 305.3+ KB


#Get Summary Statistics

In [ ]:
df.describe()

Year  Selling_Price      KM_Driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

#Seperate Dependent and Independent Variable

In [ ]:
df.columns

Index(['Brand', 'Model', 'Year', 'Selling_Price', 'KM_Driven', 'Fuel',
       'Seller_Type', 'Transmission', 'Owner'],
      dtype='object')

In [ ]:
y = df['Selling_Price']

In [ ]:
y.shape

(4340,)

In [ ]:
X = df[[ 'Fuel', 'Transmission']]

In [ ]:
X

Fuel Transmission
0     Petrol       Manual
1     Petrol       Manual
2     Diesel       Manual
3     Petrol       Manual
4     Diesel       Manual
...      ...          ...
4335  Diesel       Manual
4336  Diesel       Manual
4337  Petrol       Manual
4338  Diesel       Manual
4339  Petrol       Manual

[4340 rows x 2 columns]

#Ordinal Encoding of Categorical Features

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder()

In [ ]:
X = oe.fit_transform(X)

In [ ]:
X

array([[4., 1.],
       [4., 1.],
       [1., 1.],
       ...,
       [4., 1.],
       [1., 1.],
       [4., 1.]])

#Display Encoded Categories

In [ ]:
oe.categories_

[array(['CNG', 'Diesel', 'Electric', 'LPG', 'Petrol'], dtype=object),
 array(['Automatic', 'Manual'], dtype=object)]

**Note**

**CNG=0, Diesel=1, Electric=2, LPG=3, Petrol=4**
**Automatic=0, Manual=1**

#Get Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 2529)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3038, 2), (1302, 2), (3038,), (1302,))

#Get Model Train

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

#Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([247352.86498275, 551842.43180255, 247352.86498275, ...,
       551842.43180255, 551842.43180255, 551842.43180255])

#Get Model Evaluation

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score

In [ ]:
mean_squared_error(y_test, y_pred)

229142812008.688

In [ ]:
mean_absolute_error(y_test, y_pred)

275734.0011564797

In [ ]:
mean_absolute_percentage_error(y_test, y_pred)

0.9061945284503217

In [ ]:
r2_score(y_test, y_pred)

0.2974947304897936

#Get Future Prediction

In [ ]:
df_new = df.sample(1)

In [ ]:
df_new

Brand            Model  Year  Selling_Price  KM_Driven    Fuel  \
1590  Maruti  Maruti Alto LXi  2008          69000     100000  Petrol   

     Seller_Type Transmission        Owner  
1590  Individual       Manual  First Owner

In [ ]:
X_new = df_new[['Fuel', 'Transmission']]

In [ ]:
X_new = oe.fit_transform(X_new)

In [ ]:
X_new

array([[0., 0.]])

In [ ]:
y_pred_new = model.predict(X_new)

In [ ]:
y_pred_new

array([1653784.82946444])

This is a selling price of the cars

---

